# -*- coding: utf-8 -*-
"""코드업, 파이썬 기초 100제

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10CSrdmogtcRZvL1pAu2zEsyvrc6aVBMD
"""

a, b = input().split()
a = int(a)
b = int(b)
if a >= b:
  print('False')
else:
  print('True')

a, b = input().split()
a = int(a)
b = int(b)
print(a==b)

a, b = input().split()
a = int(a)
b = int(b)
print(b>=a)

a, b = input().split()
a = int(a)
b = int(b)
print(b!=a)

a = int(input())
if a == 0:
  print('False')
else:
  print('True')

# bool( ) 을 이용하면 입력된 식이나 값을 평가해 불 형의 값(True 또는 False)을 출력해준다.
# python 언어에서 정수값 0은 False(거짓)로 평가되고, 그 외의 값들은 모두 True(참)로 평가된다.
a = int(input())
print(bool(a))

# 참 또는 거짓의 논리값을 역(반대)으로 바꾸기 위해서 not 예약어(reserved word, keyword)를 사용할 수 있다

a = bool(int(input()))
print(not a)

# and 예약어는 주어진 두 불 값이 모두 True 일 때에만 True 로 계산하고, 나머지 경우는 False 로 계산한다.
# 이러한 논리연산을 AND 연산(boolean AND)이라고도 부르고, · 으로 표시하거나 생략하며, 집합 기호 ∩(교집합, intersection)로 표시하기도 한다.
a, b = input().split()
a = int(a)
b = int(b)
print(bool(a) and bool(b))

# or 예약어는 주어진 두 불 값 중에서 하나라도 True 이면 True 로 계산하고, 나머지 경우는 False 로 계산한다.
a, b = input().split()
a = int(a)
b = int(b)
print(bool(a) or bool(b))

# 참 거짓이 서로 다를 때에만 True 로 계산하는 논리연산을 XOR(exclusive or, 배타적 논리합) 연산이라고도 부른다.
a, b = input().split()
a = int(a)
b = int(b)
c = bool(a)
d = bool(b)
print((c and (not d)) or ((not c) and d))

# 불 값(True/False) 이 서로 같을 때에만 True 를 출력하는 프로그램을 작성해보자.
a, b = input().split()
a = int(a)
b = int(b)
print(bool(a and b) or bool((not a) and (not b)))

# 그 불 값(True/False) 이 모두 False 일 때에만 True 를 출력하는 프로그램을 작성해보자.
a, b = input().split()
a = int(a)
b = int(b)
print(bool(not a) and bool(not b))
print(not (bool(a) or bool(b)))

# 입력 된 정수를 비트단위로 참/거짓을 바꾼 후 정수로 출력해보자.
# 비트단위(bitwise)연산자 ~ 를 붙이면 된다.(~ : tilde, 틸드라고 읽는다.)
# ~(bitwise not), &(bitwise and), |(bitwise or), ^(bitwise xor), <<(bitwise left shift), >>(bitwise right shift)가 있다.
# 즉 ~를 붙이면 그냥 -1만큼 작아진 음수라고 생각해도 돼.
a = int(input())
a = ~a
print(a)

# 입력된 정수 두 개를 비트단위로 and 연산한 후 그 결과를 정수로 출력해보자.
a, b = map(int,input().split())
c = a & b
print(c)

# 입력된 정수 두 개를 비트단위로 and 연산한 후 그 결과를 정수로 출력해보자.
a, b = map(int,input().split())
c = a & b
print(c)

# 입력된 정수 두 개를 비트단위로 or 연산한 후 그 결과를 정수로 출력해보자.
a, b = map(int,input().split())
c = a | b
print(c)

# 입력된 정수 두 개를 비트단위로 xor 연산한 후 그 결과를 정수로 출력해보자.
# XOR를 만났을 때 "두 데이터에서 서로 다른 부분을 골라내고 싶구나." 생각하면 됨.
a, b = map(int,input().split())
c = a ^ b
print(c)

# 입력된 세 정수 a, b, c 중 가장 작은 값을 출력하는 프로그램을 작성해보자. 단, 3항 연산을 사용한다.
a, b, c = map(int,input().split())
d = (a if (a<=b and a<=c) else b if (b<=a and b<=c) else c)
print(d)

# 3개의 정수(a, b, c)가 입력되었을 때, 짝(even)/홀(odd)을 출력해보자.
list1 = list(map(int,input().split()))
for i in list1:
  if i % 2 == 0:
    print('even')
  else:
    print('odd')

# 0이 아닌 정수 1개가 입력되었을 때, 음(-)/양(+)과 짝(even)/홀(odd)을 구분해 분류해보자.
# 음수이면서 짝수이면, A / 음수이면서 홀수이면, B / 양수이면서 짝수이면, C / 양수이면서 홀수이면, D 를 출력한다.
a  = int(input())
if a < 0:
  if a % 2==0:
    print('A')
  else:
    print('B')
if a > 0:
  if a % 2==0:
    print('C')
  else:
    print('D')

# 점수(정수, 0 ~ 100)를 입력받아 평가를 출력해보자.
"""
평가 기준
점수 범위 : 평가
 90 ~ 100 : A
 70 ~   89 : B
 40 ~   69 : C
   0 ~   39 : D
로 평가되어야 한다.
"""
a = int(input())
if a >= 90:
  print('A')
elif a >= 70:
  print('B')
elif a >= 40:
  print('C')
else:
  print('D')

# 평가를 문자(A, B, C, D, ...)로 입력받아 내용을 다르게 출력해보자.
"""
평가 내용
평가 : 내용
A : best!!!
B : good!!
C : run!
D : slowly~
나머지 문자들 : what?
"""
a = str(input())
if a == 'A':
  print('best!!!')
elif a == 'B':
  print('good!!')
elif a == 'C':
  print('run!')
elif a == 'D':
  print('slowly~')
else:
  print('what?')

# 월이 입력될 때 계절 이름이 출력되도록 해보자.
"""
월 : 계절 이름
12, 1, 2 : winter
  3, 4, 5 : spring
  6, 7, 8 : summer
  9, 10, 11 : fall
"""
a = int(input())
winter =[12,1,2]
spring =[3,4,5]
summer = [6,7,8]
fall = [9,10,11]
if a in winter:
  print('winter')
elif a in spring:
  print('spring')
elif a in summer:
  print('summer')
elif a in fall:
  print('fall')

# 0이 아니면 입력된 정수를 출력하고, 0이 입력되면 출력을 중단해보자.
a = 0
while True:
  b = int(input())
  if b == 0:
    break
  print(b)
while True:
  b = int(input())

# 정수(1 ~ 100) 1개가 입력되었을 때 카운트다운을 출력해보자.
a = int(input())
while a >= 1:
  a -= 1
  print(a)

# 영문 소문자(a ~ z) 1개가 입력되었을 때, a부터 그 문자까지의 알파벳을 순서대로 출력해보자.
a = ord(input())
b = ord('a')
while b <= a:
  print(chr(b),end =' ')
  b+=1

# 정수(0 ~ 100) 1개를 입력받아 0부터 그 수까지 순서대로 출력해보자.
a = int(input())
b = 0
while b <=a:
  print(b)
  b+=1

# 정수(0 ~ 100) 1개를 입력받아 0부터 그 수까지 순서대로 출력해보자.
a = int(input())
for i in range(a + 1):
  print(i)

# 정수(1 ~ 100) 1개를 입력받아 1부터 그 수까지 짝수의 합을 구해보자.
a = int(input())
sum = 0
for i in range(1, a+1):
  if i % 2==0:
    sum += i
print(sum)

# 영문 소문자 'q'가 입력될 때까지 입력한 문자를 계속 출력하는 프로그램을 작성해보자.
while True:
  a = str(input())
  print(a)
  if a == 'q':
    break
while True:
  a = str(input())

# 1, 2, 3 ... 을 계속 더해 나갈 때,그 합이 입력한 정수(0 ~ 1000)보다 같거나 작을 때까지만 계속 더하는 프로그램을 작성해보자
a = int(input())
last = 0
sum = 0
for i in range(1,a+1):
  sum += i
  if sum >= a:
    last = i
    break
print(last)

# 1부터 n까지, 1부터 m까지 숫자가 적힌 서로 다른 주사위 2개를 던졌을 때, 나올 수 있는 모든 경우를 출력해보자.
n, m = map(int, input().split())
for a in range(1,n+1):
  for b in range(1,m+1):
    print(a, b)

"""
16진수(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F)를 배운
영일이는 16진수끼리 곱하는 16진수 구구단?에 대해서 궁금해졌다.

A, B, C, D, E, F 중 하나가 입력될 때,
1부터 F까지 곱한 16진수 구구단의 내용을 출력해보자.
(단, A ~ F 까지만 입력된다.)
"""
n = input()
n = int(n,16)
for i in range(1, 16):
  print('%X'%n,'*','%X'%i,'=','%X'%(n*i),sep = '')

# 친구들과 함께 3 6 9 게임을 하던 영일이는 잦은 실수 때문에 계속해서 벌칙을 받게 되었다.
# 3 6 9 게임의 왕이 되기 위한 369 마스터 프로그램을 작성해 보자.
"""
** 3 6 9 게임은?
여러 사람이 순서를 정한 후, 순서대로 수를 부르는 게임이다.
만약 3, 6, 9 가 들어간 수를 자신이 불러야 하는 상황이라면, 수를 부르는 대신 "박수(X)" 를 쳐야 한다.
33과 같이 3,6,9가 두 번 들어간 수 일때, "짝짝"과 같이 박수를 두 번 치는 형태도 있다.
"""
n = int(input())
list1 = ['3','6','9']
how_many = 0
for i in range(1, n+1):
    i = str(i)
    for a in i:
      if a in list1:
        how_many += 1
    if how_many >=1:
      print('X'*how_many, end=' ')
    else:
      print(i, end=' ')
    how_many = 0

"""
빨강(red), 초록(green), 파랑(blue) 빛을 섞어 여러 가지 다른 색 빛을 만들어 내려고 한다.

빨강(r), 초록(g), 파랑(b) 각 빛의 가짓수가 주어질 때,
주어진 rgb 빛들을 섞어 만들 수 있는 모든 경우의 조합(r g b)과 만들 수 있는 색의 가짓 수를 계산해보자.

**모니터, 스마트폰과 같은 디스플레이에서 각 픽셀의 색을 만들어내기 위해서 r, g, b 색을 조합할 수 있다.
**픽셀(pixel)은 그림(picture)을 구성하는 셀(cell)에서 이름이 만들어졌다.
"""
r, g, b = map(int, input().split())
sum = 0
for a in range(0,r):
  for k in range(0,g):
    for c in range(0,b):
      print(a,k,c)
      sum += 1
print(sum)

"""
소리가 컴퓨터에 저장될 때에는 디지털 데이터화 되어 저장된다.

마이크를 통해 1초에 적게는 수십 번, 많게는 수만 번 소리의 강약을 체크하고,
한 번씩 체크할 때 마다 그 값을 정수값으로 바꾸어 저장하는 방식으로 소리를 파일로 저장할 수 있다.

값을 저장할 때에는 비트를 사용하는 정도에 따라 세세한 녹음 정도를 결정할 수 있고,
좌우(스테레오) 채널로 저장하면 2배… 5.1채널이면 6배의 저장공간이 필요하고,
녹음 시간이 길면 그 만큼 더 많은 저장공간이 필요하다.

1초 동안 마이크로 소리강약을 체크하는 횟수를 h
(헤르쯔, Hz 는 1초에 몇 번? 체크하는가를 의미한다.)

한 번 체크한 값을 저장할 때 사용하는 비트수를 b
(2비트를 사용하면 0 또는 1 두 가지, 16비트를 사용하면 65536가지..)

좌우 등 소리를 저장할 트랙 개수인 채널 개수를 c
(모노는 1개, 스테레오는 2개의 트랙으로 저장함을 의미한다.)

녹음할 시간(초) s가 주어질 때,

필요한 저장 용량을 계산하는 프로그램을 작성해보자.
"""
h,b,c,s = map(int, input().split())
print('%.1f'%(h*b*c*s/8/1024/1024),'MB')

"""
이미지가 컴퓨터에 저장될 때에도 디지털 데이터화 되어 저장된다.

가장 기본적인 방법으로는 그림을 구성하는 한 점(pixel, 픽셀)의 색상을
빨강(r), 초록(g), 파랑(b)의 3가지의 빛의 세기 값으로 따로 변환하여 저장하는 것인데,

예를 들어 r, g, b 각 색에 대해서 8비트(0~255, 256가지 가능)씩을 사용한다고 하면,

한 점의 색상은 3가지 r, g, b의 8비트+8비트+8비트로 총 24비트로 표현해서
총 2^24 가지의 서로 다른 빛의 색깔을 사용할 수 있는 것이다.

그렇게 저장하는 점을 모아 하나의 큰 이미지를 저장할 수 있게 되는데,
1024 * 768 사이즈에 각 점에 대해 24비트로 저장하면 그 이미지를 저장하기 위한
저장 용량을 계산할 수 있다.

이렇게 이미지의 원래(raw) 데이터를 압축하지 않고 그대로 저장하는 대표적인 이미지 파일이
*.bmp 파일이며, 비트로 그림을 구성한다고 하여 비트맵 방식 또는 래스터 방식이라고 한다.

이미지의 가로 해상도 w, 세로 해상도 h, 한 픽셀을 저장하기 위한 비트 b 가 주어질 때,
압축하지 않고 저장하기 위해 필요한 저장 용량을 계산하는 프로그램을 작성해 보자.
"""
w,h,b = map(int,input().split())
print('%.2f'%(w*h*b/8/1024/1024),'MB')

"""
1, 2, 3 ... 을 순서대로 계속 더해 합을 만드는데,
그 합이 입력한 정수보다 작을 동안만 계속 더하는 프로그램을 작성해보자.

즉, 1부터 n까지 정수를 하나씩 더해 합을 만드는데,
어디까지 더해야 입력한 수보다 같거나 커지는지 알아보고자 하는 문제이다.

하지만, 이번에는 그 때 까지의 합을 출력해야 한다.

예를 들어, 57을 입력하면
1+2+3+...+8+9+10=55에서 그 다음 수인 11을 더해 66이 될 때,
그 값 66이 출력되어야 한다.
"""
a = int(input())
sum = 0
i = 0
while True:
  i +=1
  sum += i
  if sum >= a:
    print(sum)
    break

"""
1부터 입력한 정수까지 1씩 증가시켜 출력하는 프로그램을 작성하되,
3의 배수인 경우는 출력하지 않도록 만들어보자.
"""
a = int(input())
for i in range(1,a+1):
  if i % 3 != 0:
    print(i, end=' ')

"""
시작 값(a), 등차(d), 몇 번째인지를 나타내는 정수(n)가 입력될 때
n번째 수를 출력하는 프로그램을 만들어보자.
"""
a, d, n = map(int,input().split())
print(a+d*(n-1))

"""
시작 값(a), 등비(r), 몇 번째인지를 나타내는 정수(n)가 입력될 때
n번째 수를 출력하는 프로그램을 만들어보자.
"""
a, r, n = map(int,input().split())
print(a*r**(n-1))

"""
시작 값(a), 곱할 값(m), 더할 값(d),
몇 번째인지를 나타내는 정수(n)가 입력될 때,
n번째 수를 출력하는 프로그램을 만들어보자.
"""
"""
a, m, d, n = map(int, input().split())

if m == 1:
    print(a + d * (n - 1))
else:
    print(a * m**(n-1) + d * (m**(n-1) - 1) // (m-1))
"""
a, m, d, n = map(int, input().split())
before = a
for i in range(1, n):
  before = before*m + d
print(before)

"""
같은 날 동시에 가입한 3명의 사람들이 온라인 채점시스템에 들어와 문제를 푸는 날짜가
매우 규칙적이라고 할 때, 다시 모두 함께 문제를 풀게 되는 그날은 언제일까?

예를 들어 3명이 같은 날 가입/등업하고, 각각 3일마다, 7일마다, 9일마다
한 번씩 들어온다면, 처음 가입하고 63일 만에 다시 3명이 함께 문제를 풀게 된다.
"""
a, b, c = map(int,input().split())
day = 1
while day%a !=0 or day%b!=0 or day%c!=0:
  day += 1
print(day)

"""
정보 선생님은 수업을 시작하기 전에 이상한 출석을 부른다.

선생님은 출석부를 보고 번호를 부르는데,
학생들의 얼굴과 이름을 빨리 익히기 위해 번호를 무작위(랜덤)으로 부른다.

그리고 얼굴과 이름이 잘 기억되지 않는 학생들은 번호를 여러 번 불러
이름과 얼굴을 빨리 익히려고 하는 것이다.

출석 번호를 n번 무작위로 불렀을 때, 각 번호(1 ~ 23)가 불린 횟수를 각각 출력해보자.
"""
n = int(input())
a = list(map(int, input().split()))

d = []
for i in range(24):
  d.append(0)

for i in range(n):
  d[a[i]] += 1

for i in range(1,24):
  print(d[i], end=' ')

"""
정보 선생님은 수업을 시작하기 전에 이상한 출석을 부른다.

학생들의 얼굴과 이름을 빨리 익히기 위해 번호를 무작위(랜덤)으로 부르는데,
영일이는 선생님이 부른 번호들을 기억하고 있다가 거꾸로 불러보는 것을 해보고 싶어졌다.

출석 번호를 n번 무작위로 불렀을 때, 부른 번호를 거꾸로 출력해 보자.
"""
n = int(input())
a = list(map(int, input().split()))
a.reverse()
for i in a:
  print(i,end=' ')

"""
정보 선생님은 수업을 시작하기 전에 이상한 출석을 부른다.

학생들의 얼굴과 이름을 빨리 익히기 위해 번호를 무작위(랜덤)으로 부르는데,
영일이는 선생님이 부른 번호들을 기억하고 있다가 거꾸로 불러보는 것을 해보고 싶어졌다.

출석 번호를 n번 무작위로 불렀을 때, 부른 번호를 거꾸로 출력해 보자.

위에 문제 다른 풀이
"""
n = int(input())
a = list(map(int, input().split()))
for i in range(n-1,-1,-1):
  print(a[i],end=' ')

"""
정보 선생님은 오늘도 이상한 출석을 부른다.

영일이는 오늘도 다른 생각을 해보았다.
출석 번호를 다 부르지는 않은 것 같은데... 가장 빠른 번호가 뭐였지?

출석 번호를 n번 무작위로 불렀을 때, 가장 빠른 번호를 출력해 보자.
"""
n = int(input())
a = list(map(int, input().split()))

a.sort()
print(a[0])

"""
기숙사 생활을 하는 학교에서 어떤 금요일(전원 귀가일)에는 모두 집으로 귀가를 한다.

오랜만에 집에 간 영일이는 아버지와 함께 두던 매우 큰 오목에 대해서 생각해 보다가
"바둑판에 돌을 올린 것을 프로그래밍 할 수 있을까?"하고 생각하였다.

바둑판(19 * 19)에 n개의 흰 돌을 놓는다고 할 때,
n개의 흰 돌이 놓인 위치를 출력하는 프로그램을 작성해보자.
"""
baduk = []
for i in range(19):
  baduk.append([])
  for j in range(19):
    baduk[i].append(0)

n = int(input())
for i in range(n):
  x, y = map(int, input().split())
  baduk[x-1][y-1] = 1

for i in range(1,20):
  for j in range(1,20):
    print(baduk[i-1][j-1], end=' ')
  print()

"""
부모님을 기다리던 영일이는 검정/흰 색 바둑알을 바둑판에 꽉 채워 깔아 놓고 놀다가...

"십(+)자 뒤집기를 해볼까?"하고 생각했다.

십자 뒤집기는
그 위치에 있는 모든 가로줄 돌의 색을 반대(1->0, 0->1)로 바꾼 후,
다시 그 위치에 있는 모든 세로줄 돌의 색을 반대로 바꾸는 것이다.
어떤 위치를 골라 집자 뒤집기를 하면, 그 위치를 제외한 가로줄과 세로줄의 색이 모두 반대로 바뀐다.

바둑판(19 * 19)에 흰 돌(1) 또는 검정 돌(0)이 모두 꽉 채워져 놓여있을 때,
n개의 좌표를 입력받아 십(+)자 뒤집기한 결과를 출력하는 프로그램을 작성해보자.
"""
baduk = []

for i in range(19):
    baduk.append(list(map(int, input().split())))

n = int(input())

for i in range(n):
    x, y = map(int, input().split())
    for j in range(19):
        if baduk[x-1][j] == 0:
            baduk[x-1][j] = 1
        else:
            baduk[x-1][j] = 0

        if baduk[j][y-1] == 0:
            baduk[j][y-1] = 1
        else:
            baduk[j][y-1] = 0

for i in range(19):
    for j in range(19):
        print(baduk[i][j], end=' ')
    print()

"""
부모님과 함께 놀러간 영일이는
설탕과자(설탕을 녹여 물고기 등의 모양을 만든 것) 뽑기를 보게 되었다.

길이가 다른 몇 개의 막대를 바둑판과 같은 격자판에 놓는데,

막대에 있는 설탕과자 이름 아래에 있는 번호를 뽑으면 설탕과자를 가져가는 게임이었다.
(잉어, 붕어, 용 등 여러 가지가 적혀있다.)

격자판의 세로(h), 가로(w), 막대의 개수(n), 각 막대의 길이(l),
막대를 놓는 방향(d:가로는 0, 세로는 1)과
막대를 놓는 막대의 가장 왼쪽 또는 위쪽의 위치(x, y)가 주어질 때,

격자판을 채운 막대의 모양을 출력하는 프로그램을 만들어보자.

첫 줄에 격자판의 세로(h), 가로(w) 가 공백을 두고 입력되고,
두 번째 줄에 놓을 수 있는 막대의 개수(n)
세 번째 줄부터 각 막대의 길이(l), 방향(d), 좌표(x, y)가 입력된다.
1 <= w, h <= 100
1 <= n <= 10
d = 0 or 1
1 <= x <= 100-h
1 <= y <= 100-w
"""
h, w = map(int,input().split())
n = int(input())
list1 = []

# 격자판 만들기
for i in range(h):
  list1.append([])
  for j in range(w):
    list1[i].append(0)

for i in range(n):
  l, d, x, y = map(int,input().split())
  for j in range(l):
    # 막대가 가로로 놓일때
    if d == 0:
      list1[x-1][y-1] = 1
      y += 1
    else:
      list1[x-1][y-1] = 1
      x += 1

for i in range(h):
    for j in range(w):
        print(list1[i][j], end=' ')
    print()

"""
영일이는 생명과학에 관심이 생겨 왕개미를 연구하고 있었다.

왕개미를 유심히 살펴보던 중 특별히 성실해 보이는 개미가 있었는데,
그 개미는 개미굴에서 나와 먹이까지 가장 빠른 길로 이동하는 것이었다.

개미는 오른쪽으로 움직이다가 벽을 만나면 아래쪽으로 움직여 가장 빠른 길로 움직였다.
(오른쪽에 길이 나타나면 다시 오른쪽으로 움직인다.)

이에 호기심이 생긴 영일이는 그 개미를 미로 상자에 넣고 살펴보기 시작하였다.

미로 상자에 넣은 개미는 먹이를 찾았거나, 더 이상 움직일 수 없을 때까지
오른쪽 또는 아래쪽으로만 움직였다.

미로 상자의 구조가 0(갈 수 있는 곳), 1(벽 또는 장애물)로 주어지고,
먹이가 2로 주어질 때, 성실한 개미의 이동 경로를 예상해보자.

단, 맨 아래의 가장 오른쪽에 도착한 경우, 더 이상 움직일 수 없는 경우, 먹이를 찾은 경우에는
더이상 이동하지 않고 그 곳에 머무른다고 가정한다.

미로 상자의 테두리는 모두 벽으로 되어 있으며,
개미집은 반드시 (2, 2)에 존재하기 때문에 개미는 (2, 2)에서 출발한다.

10*10 크기의 미로 상자의 구조와 먹이의 위치가 입력된다.

성실한 개미가 이동한 경로를 9로 표시해 출력한다.
"""

list1 = []
x, y = 2, 2
for i in range(10):
  list1.append(list(map(int, input().split())))

while True:
  # 간 길에 먹이가 있을 경우 게임 종료
  if list1[x-1][y-1] == 2:
    list1[x-1][y-1] = 9
    break
  list1[x-1][y-1] = 9
  # 오른쪽이 벽이 아닐 경우 오른쪽으로 한 칸 이동
  if list1[x-1][y] != 1:
    y += 1
  # 오른쪽이 벽이면서 아래가 뚫려있을 경우
  elif list1[x][y-1] != 1:
    x += 1
  else:
    break

for i in range(10):
    for j in range(10):
        print(list1[i][j], end=' ')
    print()